### PR TITLE
Rewritten parser

### PR DESCRIPTION
**Pull request by rowanG077**
Completely rewritten parser to support all known(to me) C++ constucts, this includes:
	- Function pointers as parameters and as returns.
	- Template support.
	- Trailing return type.
	- Variadic templates.
	- Variadic parametes, C style and template style.
	- Correct parsing of template types with more then 1 template parameter.
	- Support for C++ operators
	- Support for C++17 attribute specifiers

### CODE REVIEW

**Comment by rowanG077** [comment]
This took me a lot longer then I expected. I actually had to start over 2 times because my approach wouldn't work for all cases but I think I got really far now. Some cases I have tested:

```
    // Test for operators, for parameter with multiple template args.
    friend matrix<T, M, N> operator-(const matrix<T, M, N>& lhs, T rhs)

    // Test for trailing rerturn type and attribute specifier
    auto foo([[augment]] int bar) const noexcept -> const char*;

    // Test for decltype as trailing return.
    auto foo2() const noexcept -> decltype(a + b

    // Function having 2 function pointers as arguments and returning a function pointer.
    int (*idputs(int (*puts)(const char *), const struct test(*str)(int *, const struct test(*str2))))(const char *);

    // Function with default parameters. With a default struct also. and being deleted
    int foo(int bar = 3, const struct mystruct baz = mystruct(10, 20)) = 0;

    // Templated function with variadic template.
    // Also with variadic arguments with c-style.
    template<typename T, typename...Args>
    T adder(T first, Args... args, ...);


    // Class template.
    template<
        typename T, std::size_t M, std::size_t N,
        typename = typename std::enable_if<std::is_arithmetic<T>::value, T>::type
    >
    class matrix;

```

**Comment by christophschlosser** [comment]
Hey!

This is **really really** impressive work!

I will take a look at this probably by tomorrow.

Thank you very much!

**Comment by rowanG077** [comment]
Thanks. I have found an issue. It doesn't work if you have function pointers that return function pointers to arbitrary nesting. I will fix this tonight.

**Comment by rowanG077** [comment]
Various issues have been found and fixed.

The following function definitions weren't working. The next commit will have them fixed:

```
	// Trailing return type with assignment.
	auto foo() -> int = 0;

	// Default argument as brace initialization 
	int foo(struct myStruct t = {})

	// Nesting foinction pointers
	int (*(*(*foo)(int))(double))(float);
```

**Comment by christophschlosser** [comment]
Regarding the UNUSED situation, I think it would be best to generate the comment for the variable and maybe add a comment stub saying UNUSED. Something like this:

```Cpp
    * bar UNUSED
```

If this is possible. If it's not possible just return the variable name.

**Comment by rowanG077** [comment]
The situation with unused is harder then it looks and there is no way we can generated a correct comment without knowing the entire preprocessor. UNUSED is an example but any macro could do dark magic there. Change the variable name. Keep the variable remove the variable. Add entire new parameters. I think in this situation to keep it simple and just show the UNUSED.

**Pull request merged**
