### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by christophschlosser**
Add first few tests to implement #24 

Will add further tests until merge

- [x] Template params
- [x] void return
- [x] no params
- [x] STL returns
- [x] STL params
- [x] CTor/DTor
- [x] Function pointers (#10, #18)
- [x] Reserved keywords (#31)

### CODE REVIEW

**Comment by christophschlosser** [comment]
@rowanG077 If you have any suggestions for tests, feel free to comment and I will add them.

**Comment by rowanG077** [comment]
Yeah I have a couple of the top of my head, probaby forgetting some at least:

Function pointers to function pointers.
Functions with trailing returns.
Functions with default arguments
Template classes/Functions.
Operators.
Functions with params that have attribute specifier sequences

```
int foo([[maybe_unused]] int bar) const;
```

Function with attribute specifiers

```
[[nodiscard]] void foo();
```

Function c-style variadic arguments
```
int foo(...);
```


Functions with C++ style variadic arguments.

```
template<typename T, typename...Args>
T adder(T first, Args... args);
```

There are a couple more but this aren't implemented properly yet:
Some operators like those mentioned in https://github.com/christophschlosser/doxdocgen/issues/28

And some I came across this week while writing a complex template:
Unnamed params

```
int foo(int, int);
```

Templates of templates:

```
template<typename T, std::size_t m, std::size_t n>
template<std::size_t p>
Matrix<T, m, p> Matrix<T, m, n>::operator*(const Matrix<T, n, p>& mat) const;
```

**Comment by rowanG077** [comment]
BTW I can assist this weekend so we could split up the work, I write test for a couple of them and you also do a couple.

**Comment by christophschlosser** [comment]
I won‘t get to a pc until tomorrow evening. So I‘m not sure how much I Van help this weekend. This is also the reason why I pushed this yesterday.
Adding new test cases should be fairly simple now. Just add a new case to `src/test/extension.test.ts` 
Adding the new features/fixing them will probably be a bit more challenging😉

**Comment by christophschlosser** [comment]
@rowanG077 I was thinking mostly alongside of features we already have. So we don't break them while adding new features, sort of regression tests.

Feel free to create issues for the features the extension is still missing

**Pull request merged**
